name: Run unit test
on: [push]
jobs:
  run-unit-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod 775 ./.github/scripts/test.sh
      - run: exec ./.github/scripts/test.sh

